version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
  settings:
    revive:
      confidence: 0.8
      rules:
        - name: exported
          disabled: true
